### ISSUE TITLE
Hamburger icon in phones

### ISSUE THREAD

**Issue by KavyaBS123** [ANSHIKA-26/HelpingHands2.0#36]
Hey @ANSHIKA-26 I am VSoC contributor 

The website doesn't seem to be resposnive in phone or other devices other than desktop. It can be still formatted properly for other devices and made good.In case of phone the hamburger icon can be added for navbar

**Comment by ANSHIKA-26** [comment]
an issue already exists for making the website responsive , please ask to be assigned in that issue
