### ISSUE TITLE
Changing layout of homepage 

### ISSUE THREAD

**Issue by Mehak-Mattoo** [ANSHIKA-26/HelpingHands2.0#42]
1. Pasting a animated picture depicting the nature of website adjacent to content.
2. Removing the image section
3. Making an accordian in FAQS section

**Comment by ANSHIKA-26** [comment]
hey , thanks for raising the issue , i have assigned it to you , kindly raise a PR with the the video of the changes you wish to do .

**Comment by Mehak-Mattoo** [comment]
Sure.

**Comment by Mehak-Mattoo** [comment]
Homepage

![1](https://github.com/ANSHIKA-26/HelpingHands2.0/assets/77096365/13d0b7bb-8f4d-4109-872c-1e1ea468b9f6)

FAQs

![3](https://github.com/ANSHIKA-26/HelpingHands2.0/assets/77096365/4a8cd94f-d686-4622-aa95-1ad2e3f7698a)

Videos of the change

https://github.com/ANSHIKA-26/HelpingHands2.0/assets/77096365/0c1e7029-9798-4dd0-85cb-07f848606d7f

**Comment by ANSHIKA-26** [comment]
looks great , do make it a pr , include the video in the pr too.

**Comment by Mehak-Mattoo** [comment]
I have made a PR and included the video :)
