### ISSUE TITLE
Bug: Apply your job & Post Job button not working

### ISSUE THREAD

**Issue by AkshatPandey-2004** [ANSHIKA-26/HelpingHands2.0#50]
After Clicking Start your Journey button and redirecting to green.html Apply your job & Post Job button not working

**Comment by ANSHIKA-26** [comment]
hey , how would u redirect it to the form page , after the register button the user has the option to do 3 things 
1. be a recruiter
2. be the job seeker
3.learn about courses

the popup serves as midway between these 3 , so i dont understand how would you be re-directing it to the form ?

**Comment by ANSHIKA-26** [comment]
the initial idea was to make a popup , which couldnt be made , if possible you can try fixing that, thank you !

**Comment by ANSHIKA-26** [comment]
im not sure, but go ahead and implement it ? lets see how it turns out :)

**Comment by ANSHIKA-26** [comment]
looks great , do make it a pr , include the video in the pr too.
