### ISSUE TITLE
Alignment of the Home Page

### ISSUE THREAD

**Issue by Harsha19-08** [ANSHIKA-26/HelpingHands2.0#67]
As the home page content was not alligned properly so make it proper can make the website good
as it was not alligned
![image](https://github.com/ANSHIKA-26/HelpingHands2.0/assets/127961910/a67199ce-209b-42da-bcf7-53f32803fad2)

**Comment by Harsha19-08** [comment]
can u assign me this issue under VSSoc 24 as i made changes u can chek this out
![image](https://github.com/ANSHIKA-26/HelpingHands2.0/assets/127961910/37ea8e00-c76d-48b1-bf89-36e57b676d6a)
![image](https://github.com/ANSHIKA-26/HelpingHands2.0/assets/127961910/47036331-8f54-4783-9d4c-912ce8c965ee)

**Comment by ANSHIKA-26** [comment]
we do not provide healthcare by any means in this website , could you please change that to employment ? do checkout the readme file for more information on what exactly we do !
